on:
  push:
  pull_request:
  
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment: whether the final installed artifact should point to staging or production apis, and whether the final artifact should be uploaded to staging or production backoffice'
        required: true
      flavor:
        description: 'Flavor: which flavor of the artifact should be created by the setup'
        required: true
      version:
        description: 'Version: the sem-ver of the artifact. Will also be appended to the setup filename'
        required: true
        type: string

jobs:
  upload-setup-artifact:
    runs-on: windows-2025
    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Checkout repository
        uses: actions/checkout@v3.5.2
      - name: Build
        run: dotnet build
      - name: Run - read args from command line and print them
        shell: pwsh
        run: |
          $env:FLAVOR="${{ github.event.inputs.flavor }}"
          $env:ENVIRONMENT="${{ github.event.inputs.environment }}"
          $env:VERSION="${{ github.event.inputs.version }}"
          echo "FLAVOR=$env:FLAVOR"
          echo "ENVIRONMENT=$env:ENVIRONMENT"
          echo "VERSION=$env:VERSION"
          dotnet run --project .\ConsoleApp\ConsoleApp.csproj -- --flavor "$env:FLAVOR" --environment "$env:ENVIRONMENT" --version "$env:VERSION"
