name: Showcase problem with windows-2025 image
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      flavor:
        description: 'Flavor of the artifact'
        required: true
        default: 'chocolate'
      environment:
        description: 'Environment (staging/production)'
        required: true
        default: 'staging'
      version:
        description: 'Version number'
        required: true
        default: '1.0.0'

jobs:
  upload-setup-artifact:
    runs-on: windows-2025
    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1.3

      - name: Checkout repository
        uses: actions/checkout@v3.5.2

      - name: Build
        run: dotnet build

      - name: Set environment variables from inputs
        run: |
          echo "flavor=${{ github.event.inputs.flavor }}" >> $GITHUB_ENV
          echo "environment=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          echo "version=${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Debug - Print environment variables
        run: |
          echo "flavor: ${{ env.flavor }}"
          echo "environment: ${{ env.environment }}"
          echo "version: ${{ env.version }}"

      - name: Run - Read args from command line and print them
        run: |
          echo "Running dotnet app with args:"
          dotnet run --project .\ConsoleApp\ConsoleApp.csproj -- --flavor "${{ env.flavor }}" --environment "${{ env.environment }}" --version "${{ env.version }}"
