name: Showcase problem with windows-2025 image

on: [push,pull_request]

jobs:
  upload-setup-artifact:
    runs-on: windows-2025
    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1.3
      - name: Checkout repository
        uses: actions/checkout@v3.5.2
      - name: Build
        run: dotnet build
      - name: Run - read args from command line and print them
        run: dotnet run --project .\ConsoleApp\ConsoleApp.csproj --flavor="${{inputs.flavor}}" --environment="${{inputs.environment}}" --version="${{inputs.version}}"
