name: Showcase problem with windows-2025 image

on: [push,pull_request]

jobs:
  upload-setup-artifact:
    runs-on: windows-2025
    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1.3

      - name: Checkout repository
        uses: actions/checkout@v3.5.2

      - name: Build
        run: dotnet build

      - name: Set environment variables
        run: |
          echo "flavor=${{secrets.flavor}}" >> $GITHUB_ENV
          echo "environment=${{secrets.environment}}" >> $GITHUB_ENV
          echo "version=${{secrets.version}}" >> $GITHUB_ENV

      - name: Debug - Print environment variables
        run: |
          echo "flavor: ${{env.flavor}}"
          echo "environment: ${{env.environment}}"
          echo "version: ${{env.version}}"

      - name: Run - Read args from command line and print them
        run: |
          # Run dotnet application with passed arguments
          dotnet run --project .\ConsoleApp\ConsoleApp.csproj -- --flavor "${{env.flavor}}" --environment "${{env.environment}}" --version "${{env.version}}"
